# Generated by Django 4.2 on 2026-02-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tAiModerationLogs',
            fields=[
                ('iLogId', models.AutoField(primary_key=True, serialize=False)),
                ('sAiLabel', models.CharField(max_length=200)),
                ('fConfidenceScore', models.FloatField(default=0.0)),
                ('jRawResponse', models.JSONField()),
                ('bReviewed', models.BooleanField(default=False)),
                ('dtCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tComments',
            fields=[
                ('iCommentId', models.AutoField(primary_key=True, serialize=False)),
                ('sContent', models.TextField()),
                ('dtCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tLikes',
            fields=[
                ('iLikeId', models.AutoField(primary_key=True, serialize=False)),
                ('dtCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tPost',
            fields=[
                ('iPostId', models.AutoField(primary_key=True, serialize=False)),
                ('sContent', models.TextField()),
                ('bIsFlagged', models.BooleanField(default=False)),
                ('fAiConfidenceScore', models.FloatField(default=0.0)),
                ('dtCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tUsers',
            fields=[
                ('iUserId', models.AutoField(primary_key=True, serialize=False)),
                ('sUserName', models.CharField(max_length=150)),
                ('sEmail', models.EmailField(max_length=254, unique=True)),
                ('sPasswordHash', models.CharField(max_length=256)),
                ('sRole', models.CharField(max_length=50)),
                ('bIsActive', models.BooleanField(default=True)),
                ('dtCreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='tpost',
            name='iUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.tusers'),
        ),
        migrations.AddField(
            model_name='tlikes',
            name='iPostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.tpost'),
        ),
        migrations.AddField(
            model_name='tlikes',
            name='iUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.tusers'),
        ),
        migrations.AddField(
            model_name='tcomments',
            name='iPostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.tpost'),
        ),
        migrations.AddField(
            model_name='tcomments',
            name='iUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.tusers'),
        ),
        migrations.AddField(
            model_name='taimoderationlogs',
            name='iPostId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.tpost'),
        ),
    ]
