# Generated by Django 4.2 on 2026-02-20 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_taimoderationlogs_tcomments_tlikes_tpost_tusers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpost',
            name='dtFlaggedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tpost',
            name='iFlaggedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_posts', to='forum.tusers'),
        ),
        migrations.AlterField(
            model_name='tusers',
            name='sRole',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
